# Generated by Django 3.2.4 on 2025-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
