# Generated by Django 3.2.4 on 2025-01-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='trip',
        ),
    ]
