# Generated by Django 3.2.4 on 2025-01-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20250123_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='activities',
        ),
        migrations.AddField(
            model_name='trip',
            name='activities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
