# Generated by Django 3.2.4 on 2025-01-25 14:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20250123_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2, null=True),
        ),
    ]
