# Generated by Django 3.2.4 on 2025-01-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
    ]
