# Generated by Django 3.2.4 on 2025-01-25 14:33

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_remove_trip_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2, null=True),
        ),
    ]
